// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svmmgrannlqsnpoclrvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2bW1ncmFubmxxc25wb2NscnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjQ5NDksImV4cCI6MjA2NTM0MDk0OX0.C4ljfqawRo-OSoXL_nIB7DRono2ynl4YlhuL6wXVXfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);